# Generated by Django 4.1.7 on 2023-03-24 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='제목')),
                ('extent', models.CharField(max_length=50, verbose_name='출판사')),
                ('description', models.TextField(max_length=500, verbose_name='소개')),
                ('charge', models.CharField(max_length=10, verbose_name='가격')),
                ('cover', models.CharField(max_length=100, verbose_name='책표지')),
                ('rights', models.CharField(max_length=50, verbose_name='저자')),
                ('issued_at', models.CharField(max_length=20, verbose_name='출판일자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('create_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.book')),
            ],
        ),
    ]
