# Generated by Django 4.1.7 on 2023-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
