# Generated by Django 4.1.7 on 2023-03-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_book_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like',
        ),
    ]
