# Generated by Django 4.1.7 on 2023-03-24 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0006_book_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
